"""The fee calculation must match the deployed n8n workflow exactly.

``tests/fixtures/reference_cases.json`` is generated by running the real Code
node bodies out of the exported workflow JSON. See docs/BACKGROUND.md.
Comparing against it turns "faithful port" into a checked property.

The tests cover the published fee table and the rules behind it, so a regression
is reported in the club's own vocabulary rather than as an opaque fixture diff.
"""

import json
from pathlib import Path

import pytest

from clubops.domain.fee import (
    billable_months,
    calculate_fee,
    format_euro,
    format_period,
    months_remaining_in_term,
    resolve_start_month,
    round2,
)
from clubops.domain.models import CivilDate, FeeConfig
from clubops.domain.timestamps import parse_timestamp

FIXTURE = Path(__file__).parent.parent / "fixtures" / "reference_cases.json"
REFERENCE_CASES = json.loads(FIXTURE.read_text())["cases"]


def _quote_for(case):
    registered_on = parse_timestamp(case["row"]["Timestamp"])
    return calculate_fee(registered_on)


@pytest.mark.parametrize("case", REFERENCE_CASES, ids=lambda c: c["label"])
def test_matches_deployed_n8n_output(case):
    """Every numeric and textual field the n8n node produced, reproduced."""
    expected = case["quote"]
    actual = _quote_for(case)

    assert actual.start_year == expected["startYear"]
    assert actual.start_month == expected["startMonth"]
    assert actual.start_month_name == expected["startMonthName"]
    assert actual.months == expected["months"]
    assert actual.period == expected["period"]
    assert actual.shifted == expected["shifted"]
    assert actual.membership_fee_standard == expected["membershipFeeStandard"]
    assert actual.membership_fee_reduced == expected["membershipFeeReduced"]
    assert actual.total_standard == expected["totalStandard"]
    assert actual.total_reduced == expected["totalReduced"]
    assert actual.calculation_line == expected["calculationLine"]


# ---------------------------------------------------------------------------
# The published fee table, reproduced exactly.
# Source: src/clubops/assets/CBT_application_form_2026_fees_v2.pdf, "valid from August 2026".
# ---------------------------------------------------------------------------

PUBLISHED_FEE_TABLE = [
    (4, "April", 6, 126, 87),
    (10, "October", 6, 126, 87),
    (5, "May", 5, 105, 72.5),
    (11, "November", 5, 105, 72.5),
    (6, "June", 4, 84, 58),
    (12, "December", 4, 84, 58),
    (7, "July", 3, 63, 43.5),
    (1, "January", 3, 63, 43.5),
    (8, "August", 2, 42, 29),
    (2, "February", 2, 42, 29),
    (9, "September", 7, 147, 101.5),
    (3, "March", 7, 147, 101.5),
]


@pytest.mark.parametrize(
    "month,name,months,standard,reduced", PUBLISHED_FEE_TABLE, ids=lambda v: str(v)
)
def test_published_fee_table(month, name, months, standard, reduced):
    # Day 1 so no cutoff shift applies — this tests the table itself.
    r = calculate_fee(CivilDate(2026, month, 1))
    assert r.months == months
    assert r.membership_fee_standard == standard
    assert r.membership_fee_reduced == reduced


def test_months_remaining_counts_the_entry_month_itself():
    assert months_remaining_in_term(4) == 6  # April: Apr..Sep
    assert months_remaining_in_term(9) == 1  # September: Sep only
    assert months_remaining_in_term(10) == 6  # October: Oct..Mar
    assert months_remaining_in_term(3) == 1  # March: Mar only
    assert months_remaining_in_term(1) == 3  # January: Jan, Feb, Mar


def test_last_month_of_a_term_rolls_into_the_whole_next_term():
    assert billable_months(9) == 7  # Sep + Oct..Mar
    assert billable_months(3) == 7  # Mar + Apr..Sep
    for m in (1, 2, 4, 5, 6, 7, 8, 10, 11, 12):
        assert billable_months(m) == months_remaining_in_term(m), f"month {m}"


def test_billable_months_stay_between_2_and_7():
    for m in range(1, 13):
        assert 2 <= billable_months(m) <= 7


def test_registrations_on_or_before_the_10th_start_in_the_current_month():
    assert resolve_start_month(CivilDate(2026, 8, 1), 10) == (2026, 8)
    assert resolve_start_month(CivilDate(2026, 8, 10), 10) == (2026, 8)


def test_registrations_after_the_10th_start_the_following_month():
    assert resolve_start_month(CivilDate(2026, 8, 11), 10) == (2026, 9)
    assert resolve_start_month(CivilDate(2026, 8, 31), 10) == (2026, 9)


def test_the_shift_rolls_the_year_over_in_december():
    assert resolve_start_month(CivilDate(2026, 12, 20), 10) == (2027, 1)
    r = calculate_fee(CivilDate(2026, 12, 20))
    assert r.start_year == 2027
    assert r.months == 3  # January -> Jan, Feb, Mar
    assert r.total_standard == 88  # 3 x 21 + 25


def test_the_shift_can_move_a_guest_across_a_term_boundary():
    # 20 September -> starts October -> a clean 6-month term, not the 7-month roll.
    late = calculate_fee(CivilDate(2026, 9, 20))
    assert late.start_month_name == "October"
    assert late.months == 6
    assert late.membership_fee_standard == 126

    # 5 September -> starts September -> 1 + 6 = 7 months.
    early = calculate_fee(CivilDate(2026, 9, 5))
    assert early.start_month_name == "September"
    assert early.months == 7
    assert early.membership_fee_standard == 147


def test_a_late_august_registration_lands_on_the_7_month_september_case():
    # Worth knowing: 20 Aug quotes 147 + 25, while 5 Aug quotes 42 + 25.
    r = calculate_fee(CivilDate(2026, 8, 20))
    assert r.start_month_name == "September"
    assert r.months == 7
    assert r.total_standard == 172


def test_the_application_fee_is_added_on_top():
    r = calculate_fee(CivilDate(2026, 8, 5))
    assert r.membership_fee_standard == 42
    assert r.application_fee == 25
    assert r.total_standard == 67
    assert r.total_reduced == 54  # 2 x 14.50 + 25


def test_the_email_arithmetic_line_matches_the_numbers():
    r = calculate_fee(CivilDate(2026, 8, 5))
    assert r.calculation_line == "2 x 21 + 25 = 67 Euros"


def test_reduced_rate_totals_avoid_floating_point_drift():
    r = calculate_fee(CivilDate(2026, 11, 3))
    assert r.membership_fee_reduced == 72.5  # 5 x 14.50, not 72.49999
    assert r.total_reduced == 97.5


def test_monthly_rates_are_parameters_not_constants():
    r = calculate_fee(
        CivilDate(2026, 8, 5),
        FeeConfig(standard_monthly_fee=18, reduced_monthly_fee=12),
    )
    assert r.membership_fee_standard == 36
    assert r.total_standard == 61  # the old 2 x 18 + 25 = 61
    assert r.membership_fee_reduced == 24


def test_application_fee_and_cutoff_day_are_also_parameters():
    no_app_fee = calculate_fee(CivilDate(2026, 8, 5), FeeConfig(application_fee=0))
    assert no_app_fee.total_standard == 42

    later_cutoff = calculate_fee(
        CivilDate(2026, 8, 15), FeeConfig(current_month_cutoff_day=20)
    )
    assert later_cutoff.start_month_name == "August"


def test_period_labels_read_correctly_including_across_a_year_boundary():
    # ASCII hyphen, matching the deployed workflow (n8n/lib/fee.js uses an en dash).
    assert format_period(2026, 8, 2) == "August - September 2026"
    assert format_period(2026, 10, 6) == "October 2026 - March 2027"
    assert format_period(2026, 9, 7) == "September 2026 - March 2027"
    assert format_period(2026, 4, 6) == "April - September 2026"
    assert format_period(2026, 9, 1) == "September 2026"


def test_invalid_input_raises_rather_than_producing_a_wrong_number():
    with pytest.raises(ValueError, match="Invalid month"):
        calculate_fee(CivilDate(2026, 13, 1))
    with pytest.raises(ValueError, match="Invalid month"):
        calculate_fee(CivilDate(2026, 0, 1))
    with pytest.raises(ValueError, match="invalid day"):
        calculate_fee(CivilDate(2026, 8, 0))


def test_round2_matches_javascript_not_bankers_rounding():
    # Python's round(0.5) is 0; Math.round(0.5) is 1. Every euro amount depends
    # on this, so assert the JS semantics directly.
    assert round2(0.005) == 0.01
    assert round2(0.015) == 0.02
    assert round2(72.5) == 72.5


def test_format_euro_writes_amounts_the_way_the_club_does():
    assert format_euro(21) == "21"
    assert format_euro(21.0) == "21"
    assert format_euro(14.5) == "14.50"
    assert format_euro(101.5) == "101.50"


def test_every_day_of_2026_produces_a_consistent_quote():
    days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    for month in range(1, 13):
        for day in range(1, days_in_month[month - 1] + 1):
            r = calculate_fee(CivilDate(2026, month, day))
            assert r.membership_fee_standard == r.months * 21, f"{day}.{month}"
            assert r.total_standard == r.months * 21 + 25, f"{day}.{month}"
            assert 2 <= r.months <= 7, f"{day}.{month} -> {r.months} months"
            assert r.period
